import type { Metadata } from "next";
import "./globals.css";

import { MobileMenu } from "@/components/nav/MobileMenu";
import { Header } from "@/components/nav/Header";
import { Footer } from "@/components/nav/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-5 bg-white">
        <MobileMenu />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
